fix: src/components/starter/projectContainer/projectContainer.tsx(106,27): error TS2551: Property 'gitHub' does not exist on type 'Project'. Did you mean 'github'?